language: python
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
  - python hi.py

deploy:
   edge: true
   provider: bluemixcloudfoundry
   username: edreir@br.ibm.com
   password: Ukilops1
   organization: edreir@br.ibm.com
   space: dev
   manifest: manifest.yml          # (optional)  Defaults to manifest.yml.
   on:
     branch: master

